### ISSUE TITLE
BUG Autograde results sorting doesn't work with pagination

### ISSUE THREAD

**Issue by PIG208** [AnubisLMS/Anubis#337]
Related
- `web/src/pages/core/admin/Autograde/Results.jsx`
- `api/anubis/views/admin/autograde.py`

When the data grid is sorted in a different order, we get rows of undefined submissions if they have not been fetched before. Currently, the offset + limit pagination API only supports fetching data sequentially in an unsorted order.

![image](https://user-images.githubusercontent.com/39874143/152599096-bbd8cd48-816d-48b4-8196-8c3163b75ae6.png)

**Comment by wabscale** [comment]
Hey which browser is this on?

**Comment by wabscale** [comment]
Oh ok this is because we only load the autograde results for the page you are on. So its a list of autograde entries that are empty until you load the page its on. I'm pushing something so we pull them all at once.

We did this because the autograde results caching used to be significantly less efficient than it is now.

**Comment by wabscale** [comment]
https://github.com/AnubisLMS/Anubis/commit/2c779274fe24054196047628493fc0701cd19d85

**Comment by PIG208** [comment]
Didn't expect to remove pagination altogether. But it's fine as long as it works.
